version: "3.3"

services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=films-manager
      - MYSQL_USER=root
      - MYSQL_PASSWORD=admin123
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PORT=3306
    ports:
      - "3306:3306"
    volumes:
      - "./mysql_data:/var/lib/mysql"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - PMA_HOST=mysql
    ports:
      - 8080:80
